export const liquidGlassStudioDefaultControls = {
  blurEdge: true,
  blurRadius: 1,
  glareAngle: -45,
  glareConvergence: 50,
  glareFactor: 90,
  glareHardness: 20,
  glareOppositeFactor: 80,
  glareRange: 30,
  mergeRate: 0.05,
  refDispersion: 7,
  refFactor: 1.4,
  refFresnelFactor: 20,
  refFresnelHardness: 20,
  refFresnelRange: 30,
  refThickness: 20,
  shadowExpand: 25,
  shadowFactor: 15,
  shadowPosition: { x: 0, y: -10 },
  shapeHeight: 200,
  shapeRadius: 80,
  shapeRoundness: 5,
  shapeWidth: 200,
  showShape1: true,
  step: 9,
  tint: { a: 0, b: 255, g: 255, r: 255 },
} as const;
