"""Public organization management interface."""

from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from kernelon_api.modules.organizations.domain import Principal


@runtime_checkable
class OrganizationService(Protocol):
    async def get_current_profile(self, user_id: UUID) -> dict[str, Any]: ...
    async def principal(
        self, user_id: UUID, organization_id: UUID, permission: str
    ) -> Principal: ...
    async def list_organizations(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def get_organization(self, principal: Principal) -> dict[str, Any]: ...
    async def update_organization(self, principal: Principal, name: str) -> dict[str, Any]: ...
    async def list_members(
        self, principal: Principal, page: int, page_size: int, search: str | None
    ) -> dict[str, Any]: ...
    async def get_member(self, principal: Principal, member_id: UUID) -> dict[str, Any]: ...
    async def create_member(
        self, principal: Principal, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def update_member(
        self, principal: Principal, member_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def set_member_status(
        self, principal: Principal, member_id: UUID, status: str
    ) -> dict[str, Any]: ...
    async def replace_member_groups(
        self, principal: Principal, member_id: UUID, ids: list[UUID]
    ) -> dict[str, Any]: ...
    async def replace_member_roles(
        self, principal: Principal, member_id: UUID, ids: list[UUID]
    ) -> dict[str, Any]: ...
    async def list_groups(self, principal: Principal) -> list[dict[str, Any]]: ...
    async def create_group(
        self, principal: Principal, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def update_group(
        self, principal: Principal, group_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def replace_group_members(
        self, principal: Principal, group_id: UUID, ids: list[UUID]
    ) -> dict[str, Any]: ...
    async def replace_group_roles(
        self, principal: Principal, group_id: UUID, ids: list[UUID]
    ) -> dict[str, Any]: ...
    async def list_roles(self, principal: Principal) -> list[dict[str, Any]]: ...
    async def create_role(self, principal: Principal, values: dict[str, Any]) -> dict[str, Any]: ...
    async def update_role(
        self, principal: Principal, role_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
