"""Public music application and provider interfaces."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Mapping, Sequence
    from uuid import UUID

    from kernelon_api.modules.music.domain import (
        BeatMapCacheStatus,
        MusicAppInfo,
        MusicDiscoverHome,
    )


class MusicProviderError(RuntimeError):
    """An upstream provider failed to return a usable response."""


class UnsafeProxyUrlError(ValueError):
    """A media proxy URL could reach a non-public network destination."""


@dataclass(frozen=True, slots=True)
class ProviderStream:
    """An upstream body that remains open until its iterator is exhausted."""

    status_code: int
    headers: Mapping[str, str]
    body: AsyncIterator[bytes]


@dataclass(frozen=True, slots=True)
class MusicJsonResult:
    """Source-compatible JSON payload and status code."""

    payload: Mapping[str, Any]
    status_code: int = 200


@dataclass(frozen=True, slots=True)
class MusicProviderResponse:
    """Provider JSON plus any authentication cookie returned out-of-band."""

    payload: Mapping[str, Any]
    cookie: str = ""


@dataclass(frozen=True, slots=True)
class MusicAccountSession:
    """Provider-isolated credentials for one authenticated KernelOn user."""

    cookie: str = ""
    qq_cookie: str = ""


type MusicAccountProvider = Literal["netease", "qq"]


@dataclass(frozen=True, slots=True)
class MusicProxyResult:
    """Sanitized streaming response returned to the presentation layer."""

    status_code: int
    headers: Mapping[str, str]
    body: AsyncIterator[bytes]


@runtime_checkable
class MusicProviderHttpPort(Protocol):
    """HTTP boundary for the exact Netease calls used by Mineradio."""

    async def cloud_search(
        self, keywords: str, limit: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def song_details(self, ids: Sequence[str], cookie: str = "") -> Mapping[str, Any]: ...
    async def lyric_new(self, song_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def lyric(self, song_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def playlist_tracks_all(
        self, playlist_id: str, limit: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def playlist_detail(self, playlist_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def artist_detail(self, artist_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def artist_songs(
        self, artist_id: str, limit: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def artist_top_songs(self, artist_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def song_comments(
        self, song_id: str, limit: int, offset: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def weather_geocode(self, query: str) -> Mapping[str, Any]: ...
    async def weather_forecast(
        self, latitude: float, longitude: float, timezone: str
    ) -> Mapping[str, Any]: ...
    async def weather_ip_location(self) -> Mapping[str, Any]: ...
    async def podcast_search(
        self, keywords: str, limit: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def podcast_hot(self, limit: int, offset: int, cookie: str = "") -> Mapping[str, Any]: ...
    async def podcast_detail(self, radio_id: str, cookie: str = "") -> Mapping[str, Any]: ...
    async def podcast_programs(
        self, radio_id: str, limit: int, offset: int, cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def personalized(self, limit: int, cookie: str) -> Mapping[str, Any]: ...
    async def recommend_resource(self, cookie: str) -> Mapping[str, Any]: ...
    async def recommend_songs(self, cookie: str) -> Mapping[str, Any]: ...
    async def proxy_stream(
        self,
        url: str,
        *,
        method: str,
        headers: Mapping[str, str],
    ) -> ProviderStream: ...


@runtime_checkable
class NeteaseAccountProviderPort(Protocol):
    """Exact Netease calls used by Mineradio's account and write routes."""

    async def login_qr_key(self) -> MusicProviderResponse: ...
    async def login_qr_check(self, key: str, *, cookie: str = "") -> MusicProviderResponse: ...
    async def login_status(self, cookie: str) -> MusicProviderResponse: ...
    async def user_account(self, cookie: str) -> MusicProviderResponse: ...
    async def logout(self, cookie: str) -> MusicProviderResponse: ...
    async def user_playlists(
        self, user_id: str, limit: int, cookie: str
    ) -> MusicProviderResponse: ...
    async def song_url_v1(self, song_id: str, level: str, cookie: str) -> MusicProviderResponse: ...
    async def song_url(self, song_id: str, bitrate: int, cookie: str) -> MusicProviderResponse: ...
    async def song_like_check(
        self, song_ids: Sequence[str], cookie: str
    ) -> MusicProviderResponse: ...
    async def like_list(self, user_id: str, cookie: str) -> MusicProviderResponse: ...
    async def like_song(self, song_id: str, like: bool, cookie: str) -> MusicProviderResponse: ...
    async def create_playlist(
        self, name: str, privacy: str, cookie: str
    ) -> MusicProviderResponse: ...
    async def add_playlist_tracks(
        self, playlist_id: str, song_ids: str, cookie: str
    ) -> MusicProviderResponse: ...
    async def add_playlist_tracks_fallback(
        self, playlist_id: str, song_ids: str, cookie: str
    ) -> MusicProviderResponse: ...


@runtime_checkable
class PodcastAccountProviderPort(Protocol):
    async def login_status(self, cookie: str) -> MusicProviderResponse: ...
    async def user_account(self, cookie: str) -> MusicProviderResponse: ...
    async def podcast_sublist(
        self, limit: int, offset: int, cookie: str
    ) -> MusicProviderResponse: ...
    async def podcast_created(self, user_id: str, cookie: str) -> MusicProviderResponse: ...
    async def podcast_paid(self, limit: int, offset: int, cookie: str) -> MusicProviderResponse: ...
    async def podcast_liked(self, cookie: str) -> MusicProviderResponse: ...
    async def podcast_recent_voices(self, limit: int, cookie: str) -> MusicProviderResponse: ...


@runtime_checkable
class QQMusicProviderPort(Protocol):
    """Direct QQ Music boundary; cookies are always supplied per KernelOn user."""

    async def qq_get(
        self, url: str, params: Mapping[str, str | int], cookie: str = ""
    ) -> Mapping[str, Any]: ...
    async def qq_musicu(
        self, payload: Mapping[str, Any], cookie: str = ""
    ) -> Mapping[str, Any]: ...


@runtime_checkable
class MusicAccountSessionPort(Protocol):
    """Application-owned account-session boundary; never a process-wide cookie."""

    async def load(self, kernelon_user_id: UUID) -> MusicAccountSession: ...
    async def save(self, kernelon_user_id: UUID, session: MusicAccountSession) -> None: ...
    async def save_provider(
        self, kernelon_user_id: UUID, provider: MusicAccountProvider, cookie: str
    ) -> None: ...
    async def clear(self, kernelon_user_id: UUID) -> None: ...


@runtime_checkable
class NeteaseAccountService(Protocol):
    """Mineradio-compatible Netease account use cases."""

    async def import_cookie(self, user_id: UUID, raw_cookie: object) -> MusicJsonResult: ...
    async def create_qr_key(self, user_id: UUID) -> MusicJsonResult: ...
    async def create_qr_code(self, user_id: UUID, key: str) -> MusicJsonResult: ...
    async def check_qr_code(self, user_id: UUID, key: str) -> MusicJsonResult: ...
    async def get_login_status(self, user_id: UUID) -> MusicJsonResult: ...
    async def logout(self, user_id: UUID) -> MusicJsonResult: ...
    async def get_user_playlists(self, user_id: UUID, limit: int) -> MusicJsonResult: ...
    async def get_song_url(self, user_id: UUID, song_id: str, quality: str) -> MusicJsonResult: ...
    async def check_song_likes(self, user_id: UUID, song_ids: Sequence[str]) -> MusicJsonResult: ...
    async def set_song_like(self, user_id: UUID, song_id: str, like: bool) -> MusicJsonResult: ...
    async def create_playlist(self, user_id: UUID, name: str, privacy: str) -> MusicJsonResult: ...
    async def add_song_to_playlist(
        self, user_id: UUID, playlist_id: str, song_ids: str
    ) -> MusicJsonResult: ...


@runtime_checkable
class QQMusicService(Protocol):
    async def search(self, user_id: UUID, keywords: str, limit: int) -> MusicJsonResult: ...
    async def song_url(
        self, user_id: UUID, mid: str, media_mid: str, quality: str
    ) -> MusicJsonResult: ...
    async def lyric(self, user_id: UUID, mid: str, song_id: str) -> MusicJsonResult: ...
    async def login_status(self, user_id: UUID) -> MusicJsonResult: ...
    async def import_cookie(self, user_id: UUID, raw_cookie: object) -> MusicJsonResult: ...
    async def logout(self, user_id: UUID) -> MusicJsonResult: ...
    async def user_playlists(self, user_id: UUID) -> MusicJsonResult: ...
    async def playlist_tracks(self, user_id: UUID, playlist_id: str) -> MusicJsonResult: ...
    async def artist_detail(self, user_id: UUID, mid: str, limit: int) -> MusicJsonResult: ...
    async def song_comments(
        self, user_id: UUID, song_id: str, mid: str, limit: int, offset: int
    ) -> MusicJsonResult: ...


@runtime_checkable
class PodcastAccountService(Protocol):
    async def collections(self, user_id: UUID) -> MusicJsonResult: ...
    async def collection_items(
        self, user_id: UUID, key: str, limit: int, offset: int
    ) -> MusicJsonResult: ...


@runtime_checkable
class MusicService(Protocol):
    """Use cases available from the KernelOn music backend."""

    async def get_app_info(self) -> MusicAppInfo: ...
    async def get_beat_map_cache_status(self) -> BeatMapCacheStatus: ...
    async def get_discover_home(self, user_id: UUID) -> MusicDiscoverHome: ...
    async def search(self, user_id: UUID, keywords: str, limit: int) -> MusicJsonResult: ...
    async def get_lyric(self, user_id: UUID, song_id: str) -> MusicJsonResult: ...
    async def get_playlist_tracks(self, user_id: UUID, playlist_id: str) -> MusicJsonResult: ...
    async def get_artist_detail(
        self, user_id: UUID, artist_id: str, limit: int
    ) -> MusicJsonResult: ...
    async def get_song_comments(
        self, user_id: UUID, song_id: str, limit: int, offset: int
    ) -> MusicJsonResult: ...
    async def get_weather_radio(
        self,
        user_id: UUID,
        *,
        city: str,
        latitude: str | None,
        longitude: str | None,
        timezone: str,
    ) -> MusicJsonResult: ...
    async def get_weather_ip_location(self) -> MusicJsonResult: ...
    async def search_podcasts(
        self, user_id: UUID, keywords: str, limit: int
    ) -> MusicJsonResult: ...
    async def get_hot_podcasts(self, user_id: UUID, limit: int, offset: int) -> MusicJsonResult: ...
    async def get_podcast_detail(self, user_id: UUID, radio_id: str) -> MusicJsonResult: ...
    async def get_podcast_programs(
        self, user_id: UUID, radio_id: str, limit: int, offset: int
    ) -> MusicJsonResult: ...
    async def proxy_cover(self, url: str, *, method: str) -> MusicProxyResult: ...
    async def proxy_audio(
        self, url: str, *, method: str, range_header: str
    ) -> MusicProxyResult: ...
