"""Wallpaper application ports."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from uuid import UUID

    from kernelon_api.modules.wallpapers.domain import WallpaperAsset


class WallpaperProvider(Protocol):
    key: str

    async def search(
        self, query: str, media_type: str, page: int, limit: int
    ) -> list[WallpaperAsset]: ...
    async def get(self, external_id: str) -> WallpaperAsset | None: ...


class WallpaperService(Protocol):
    async def search(
        self, user_id: UUID, query: str, media_type: str, page: int, limit: int
    ) -> dict[str, Any]: ...
    async def get_asset(self, user_id: UUID, asset_id: str) -> dict[str, Any]: ...
    async def sources(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def update_source(
        self, user_id: UUID, source_id: str, enabled: bool
    ) -> dict[str, Any]: ...
    async def set_source_preference(
        self, user_id: UUID, source_id: str, visible: bool
    ) -> dict[str, Any]: ...
    async def current(self, user_id: UUID) -> dict[str, Any] | None: ...
    async def apply(self, user_id: UUID, asset: dict[str, Any]) -> dict[str, Any]: ...
    async def favorite(
        self, user_id: UUID, asset: dict[str, Any], liked: bool
    ) -> dict[str, Any]: ...
    async def storage(self, user_id: UUID) -> dict[str, Any]: ...
    async def create_upload(self, user_id: UUID, values: dict[str, Any]) -> dict[str, Any]: ...
    async def write_upload(self, user_id: UUID, upload_id: UUID, body: bytes) -> dict[str, Any]: ...
    async def delete_upload(self, user_id: UUID, upload_id: UUID) -> None: ...
    async def media(self, user_id: UUID, asset_id: UUID) -> tuple[bytes, str]: ...
    async def import_asset(self, user_id: UUID, asset_id: str, confirm: bool) -> dict[str, Any]: ...
