"""Lifecycle application interface."""

from typing import Any, Protocol, runtime_checkable
from uuid import UUID

from kernelon_api.modules.organizations.domain import Principal


@runtime_checkable
class LifecycleService(Protocol):
    async def dashboard(self, principal: Principal) -> dict[str, Any]: ...
    async def list_cases(
        self, principal: Principal, search: str | None, status: str | None, risk: str | None
    ) -> list[dict[str, Any]]: ...
    async def get_case(self, principal: Principal, case_id: UUID) -> dict[str, Any]: ...
    async def create_case(self, principal: Principal, values: dict[str, Any]) -> dict[str, Any]: ...
    async def transition_case(
        self, principal: Principal, case_id: UUID, target: str, reason: str | None
    ) -> dict[str, Any]: ...
    async def list_templates(self, principal: Principal) -> list[dict[str, Any]]: ...
    async def create_template(
        self, principal: Principal, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def list_mentors(self, principal: Principal) -> list[dict[str, Any]]: ...
    async def upsert_mentor(
        self, principal: Principal, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def assign_mentor(
        self, principal: Principal, case_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def update_task(
        self, principal: Principal, case_id: UUID, task_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def create_checkin(
        self, principal: Principal, case_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def update_action(
        self, principal: Principal, case_id: UUID, action_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def create_assessment(
        self, principal: Principal, case_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def submit_assessment(
        self, principal: Principal, case_id: UUID, round_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def decide_assessment(
        self, principal: Principal, case_id: UUID, round_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
    async def resolve_risk(
        self, principal: Principal, case_id: UUID, risk_id: UUID, values: dict[str, Any]
    ) -> dict[str, Any]: ...
